//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nu34life.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plan()
        {
            this.Plans_Recipes = new HashSet<Plans_Recipes>();
        }
    
        public int Id { get; set; }
        public int Description { get; set; }
        public int State_Id { get; set; }
    
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plans_Recipes> Plans_Recipes { get; set; }

        public ICollection<Plans_Recipes> getPlanRecipe()
        {
            return this.Plans_Recipes;
        }

        public void setPlanRecipe(ICollection<Plans_Recipes> Plans_Recipes)
        {
            this.Plans_Recipes = Plans_Recipes;
        }
    }
}
