//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nu34life.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plans_Recipes
    {
        public int Id { get; set; }
        public string Turn { get; set; }
        public System.DateTime Date { get; set; }
        public int Recipe_Id { get; set; }
        public int Plan_Id { get; set; }

        public void setPlan(Plan p)
        {
            this.Plan = p;
        }
        public void setPlan_Id(int Plan)
        {
            this.Plan_Id = Plan;
        }


        public virtual Plan Plan { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
