//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nu34life.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe_Details
    {
        public int Recipe_Id { get; set; }
        public int Ingredient_Id { get; set; }
        public decimal Grams { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Recipe Recipe { get; set; }


        public Recipe GetRecipe()
        {
           return  this.Recipe;
        }
    }
}
