//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nu34life.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public State()
        {
            this.Plans = new HashSet<Plan>();
            this.Drugs = new HashSet<Drug>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int Height { get; set; }
        public int Weighr { get; set; }
        public int Glucose { get; set; }
        public bool Affiliate { get; set; }
        public System.DateTime Generated_day { get; set; }
        public System.DateTime Expiration { get; set; }
        public int Nutritionist_Id { get; set; }
        public int Patient_Id { get; set; }
        public void setPatient_ID(int v)
        {
            this.Patient_Id = v;
        }
        public void setNutritionist_ID(int v)
        {
            this.Nutritionist_Id = v;
        }

        public virtual Nutritionist Nutritionist { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan> Plans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drug> Drugs { get; set; }
    }
}
